image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - test
  - publish

branch::test:
  stage: test
  except:
    - tags
  script: |
    cd src
    dotnet test -v minimal -c Release /p:CollectCoverage=true

branch::publish:
  stage: publish
  only:
    - tags
  script: |
    cd src

    echo ---------------------------------------------- TESTING

    dotnet test -v minimal -c Release /p:CollectCoverage=true

    echo ---------------------------------------------- VERSIONING

    echo VERSION := $CI_COMMIT_TAG

    sed -i -- "s/1\.0\.0\.0/${CI_COMMIT_TAG}/g" ./RollsEngine/RollsEngine.csproj
    sed -i -- "s/1\.0\.0\.0/${CI_COMMIT_TAG}/g" ./RollsEngine.Newtonsoft/RollsEngine.Newtonsoft.csproj

    echo ---------------------------------------------- BUILDING

    cd RollsEngine
    dotnet pack -c Release
    cd ..

    cd RollsEngine.Newtonsoft
    dotnet pack -c Release
    cd ..

    echo ---------------------------------------------- PUBLISHING

    cd RollsEngine/bin/Release
    NUGET_PKG=$(ls *.nupkg)
    echo PACKAGE := $NUGET_PKG
    dotnet nuget push $NUGET_PKG -k $NUGET_KEY -s https://api.nuget.org/v3/index.json
    cd ../../..

    cd RollsEngine.Newtonsoft/bin/Release
    NUGET_PKG=$(ls *.nupkg)
    echo PACKAGE := $NUGET_PKG
    dotnet nuget push $NUGET_PKG -k $NUGET_KEY -s https://api.nuget.org/v3/index.json
    cd ../../..
